//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплата.
    /// </summary>
    // *** Start programmer edit section *** (Оплата CustomAttributes)

    // *** End programmer edit section *** (Оплата CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОплатаE", new string[] {
            "КодОплаты as \'Код оплаты\'",
            "Способ as \'Способ\'",
            "Сумма as \'Сумма\'",
            "Статус as \'Статус\'",
            "Дата as \'Дата\'",
            "Заказ as \'Заказ\'",
            "Заказ.КодЗаказа as \'Код заказа\'"}, Hidden=new string[] {
            "Заказ.КодЗаказа"})]
    [MasterViewDefineAttribute("ОплатаE", "Заказ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодЗаказа")]
    [View("ОплатаL", new string[] {
            "КодОплаты as \'Код оплаты\'",
            "Способ as \'Способ\'",
            "Сумма as \'Сумма\'",
            "Статус as \'Статус\'",
            "Дата as \'Дата\'",
            "Заказ.КодЗаказа as \'Код заказа\'"})]
    public class Оплата : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодОплаты;
        
        private IIS.Kursovaya.СпособОплаты fСпособ;
        
        private double fСумма;
        
        private IIS.Kursovaya.СтатусОплаты fСтатус;
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (Оплата CustomMembers)

        // *** End programmer edit section *** (Оплата CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Дата CustomAttributes)

        // *** End programmer edit section *** (Оплата.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Дата Get start)

                // *** End programmer edit section *** (Оплата.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Оплата.Дата Get end)

                // *** End programmer edit section *** (Оплата.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Дата Set start)

                // *** End programmer edit section *** (Оплата.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Оплата.Дата Set end)

                // *** End programmer edit section *** (Оплата.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.КодОплаты CustomAttributes)

        // *** End programmer edit section *** (Оплата.КодОплаты CustomAttributes)
        public virtual int КодОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.КодОплаты Get start)

                // *** End programmer edit section *** (Оплата.КодОплаты Get start)
                int result = this.fКодОплаты;
                // *** Start programmer edit section *** (Оплата.КодОплаты Get end)

                // *** End programmer edit section *** (Оплата.КодОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.КодОплаты Set start)

                // *** End programmer edit section *** (Оплата.КодОплаты Set start)
                this.fКодОплаты = value;
                // *** Start programmer edit section *** (Оплата.КодОплаты Set end)

                // *** End programmer edit section *** (Оплата.КодОплаты Set end)
            }
        }
        
        /// <summary>
        /// Способ.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Способ CustomAttributes)

        // *** End programmer edit section *** (Оплата.Способ CustomAttributes)
        public virtual IIS.Kursovaya.СпособОплаты Способ
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Способ Get start)

                // *** End programmer edit section *** (Оплата.Способ Get start)
                IIS.Kursovaya.СпособОплаты result = this.fСпособ;
                // *** Start programmer edit section *** (Оплата.Способ Get end)

                // *** End programmer edit section *** (Оплата.Способ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Способ Set start)

                // *** End programmer edit section *** (Оплата.Способ Set start)
                this.fСпособ = value;
                // *** Start programmer edit section *** (Оплата.Способ Set end)

                // *** End programmer edit section *** (Оплата.Способ Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Статус CustomAttributes)

        // *** End programmer edit section *** (Оплата.Статус CustomAttributes)
        public virtual IIS.Kursovaya.СтатусОплаты Статус
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Статус Get start)

                // *** End programmer edit section *** (Оплата.Статус Get start)
                IIS.Kursovaya.СтатусОплаты result = this.fСтатус;
                // *** Start programmer edit section *** (Оплата.Статус Get end)

                // *** End programmer edit section *** (Оплата.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Статус Set start)

                // *** End programmer edit section *** (Оплата.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Оплата.Статус Set end)

                // *** End programmer edit section *** (Оплата.Статус Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Сумма CustomAttributes)

        // *** End programmer edit section *** (Оплата.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Сумма Get start)

                // *** End programmer edit section *** (Оплата.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Оплата.Сумма Get end)

                // *** End programmer edit section *** (Оплата.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Сумма Set start)

                // *** End programmer edit section *** (Оплата.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Оплата.Сумма Set end)

                // *** End programmer edit section *** (Оплата.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Заказ CustomAttributes)

        // *** End programmer edit section *** (Оплата.Заказ CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказ"})]
        [NotNull()]
        public virtual IIS.Kursovaya.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Заказ Get start)

                // *** End programmer edit section *** (Оплата.Заказ Get start)
                IIS.Kursovaya.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (Оплата.Заказ Get end)

                // *** End programmer edit section *** (Оплата.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Заказ Set start)

                // *** End programmer edit section *** (Оплата.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (Оплата.Заказ Set end)

                // *** End programmer edit section *** (Оплата.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОплатаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаE", typeof(IIS.Kursovaya.Оплата));
                }
            }
            
            /// <summary>
            /// "ОплатаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаL", typeof(IIS.Kursovaya.Оплата));
                }
            }
        }
    }
}
