//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус заказа.
    /// </summary>
    // *** Start programmer edit section *** (СтатусЗаказа CustomAttributes)

    // *** End programmer edit section *** (СтатусЗаказа CustomAttributes)
    public enum СтатусЗаказа
    {
        
        // *** Start programmer edit section *** (СтатусЗаказа.1 CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаказа.1 CustomAttributes)
        [Caption("Поставлен в очередь")]
        1,
        
        // *** Start programmer edit section *** (СтатусЗаказа.2 CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаказа.2 CustomAttributes)
        [Caption("Собран")]
        2,
        
        // *** Start programmer edit section *** (СтатусЗаказа.3 CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаказа.3 CustomAttributes)
        [Caption("Отправлен")]
        3,
    }
}
