//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус оплаты.
    /// </summary>
    // *** Start programmer edit section *** (СтатусОплаты CustomAttributes)

    // *** End programmer edit section *** (СтатусОплаты CustomAttributes)
    public enum СтатусОплаты
    {
        
        // *** Start programmer edit section *** (СтатусОплаты.Оплачено CustomAttributes)

        // *** End programmer edit section *** (СтатусОплаты.Оплачено CustomAttributes)
        [Caption("Оплачено")]
        Оплачено,
        
        // *** Start programmer edit section *** (СтатусОплаты.НеОплачено CustomAttributes)

        // *** End programmer edit section *** (СтатусОплаты.НеОплачено CustomAttributes)
        [Caption("Не оплачено")]
        НеОплачено,
    }
}
