//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "КодТовара as \'Код товара\'",
            "Наименование as \'Наименование\'",
            "Изображение as \'Изображение\'",
            "Цена as \'Цена\'",
            "Свойства as \'Свойства\'",
            "Производитель as \'Производитель\'",
            "Производитель.Производитель as \'Производитель\'",
            "Поставщик as \'Поставщик\'",
            "Поставщик.Поствщик as \'Поствщик\'"}, Hidden=new string[] {
            "Производитель.Производитель",
            "Поставщик.Поствщик"})]
    [MasterViewDefineAttribute("ТоварE", "Производитель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Производитель")]
    [MasterViewDefineAttribute("ТоварE", "Поставщик", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Поствщик")]
    [View("ТоварL", new string[] {
            "КодТовара as \'Код товара\'",
            "Наименование as \'Наименование\'",
            "Изображение as \'Изображение\'",
            "Цена as \'Цена\'",
            "Свойства as \'Свойства\'",
            "Производитель.Производитель as \'Производитель\'",
            "Поставщик.Поствщик as \'Поствщик\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодТовара;
        
        private string fНаименование;
        
        private string fИзображение;
        
        private double fЦена;
        
        private string fСвойства;
        
        private IIS.Kursovaya.Производитель fПроизводитель;
        
        private IIS.Kursovaya.Поставщик fПоставщик;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// Изображение.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Изображение CustomAttributes)

        // *** End programmer edit section *** (Товар.Изображение CustomAttributes)
        [StrLen(255)]
        public virtual string Изображение
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Изображение Get start)

                // *** End programmer edit section *** (Товар.Изображение Get start)
                string result = this.fИзображение;
                // *** Start programmer edit section *** (Товар.Изображение Get end)

                // *** End programmer edit section *** (Товар.Изображение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Изображение Set start)

                // *** End programmer edit section *** (Товар.Изображение Set start)
                this.fИзображение = value;
                // *** Start programmer edit section *** (Товар.Изображение Set end)

                // *** End programmer edit section *** (Товар.Изображение Set end)
            }
        }
        
        /// <summary>
        /// КодТовара.
        /// </summary>
        // *** Start programmer edit section *** (Товар.КодТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.КодТовара CustomAttributes)
        public virtual int КодТовара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.КодТовара Get start)

                // *** End programmer edit section *** (Товар.КодТовара Get start)
                int result = this.fКодТовара;
                // *** Start programmer edit section *** (Товар.КодТовара Get end)

                // *** End programmer edit section *** (Товар.КодТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.КодТовара Set start)

                // *** End programmer edit section *** (Товар.КодТовара Set start)
                this.fКодТовара = value;
                // *** Start programmer edit section *** (Товар.КодТовара Set end)

                // *** End programmer edit section *** (Товар.КодТовара Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Наименование CustomAttributes)

        // *** End programmer edit section *** (Товар.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Наименование Get start)

                // *** End programmer edit section *** (Товар.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Товар.Наименование Get end)

                // *** End programmer edit section *** (Товар.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Наименование Set start)

                // *** End programmer edit section *** (Товар.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Товар.Наименование Set end)

                // *** End programmer edit section *** (Товар.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Свойства.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Свойства CustomAttributes)

        // *** End programmer edit section *** (Товар.Свойства CustomAttributes)
        [StrLen(255)]
        public virtual string Свойства
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Свойства Get start)

                // *** End programmer edit section *** (Товар.Свойства Get start)
                string result = this.fСвойства;
                // *** Start programmer edit section *** (Товар.Свойства Get end)

                // *** End programmer edit section *** (Товар.Свойства Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Свойства Set start)

                // *** End programmer edit section *** (Товар.Свойства Set start)
                this.fСвойства = value;
                // *** Start programmer edit section *** (Товар.Свойства Set end)

                // *** End programmer edit section *** (Товар.Свойства Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Цена CustomAttributes)

        // *** End programmer edit section *** (Товар.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Цена Get start)

                // *** End programmer edit section *** (Товар.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Товар.Цена Get end)

                // *** End programmer edit section *** (Товар.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Цена Set start)

                // *** End programmer edit section *** (Товар.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Товар.Цена Set end)

                // *** End programmer edit section *** (Товар.Цена Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Поставщик CustomAttributes)

        // *** End programmer edit section *** (Товар.Поставщик CustomAttributes)
        [PropertyStorage(new string[] {
                "Поставщик"})]
        [NotNull()]
        public virtual IIS.Kursovaya.Поставщик Поставщик
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Поставщик Get start)

                // *** End programmer edit section *** (Товар.Поставщик Get start)
                IIS.Kursovaya.Поставщик result = this.fПоставщик;
                // *** Start programmer edit section *** (Товар.Поставщик Get end)

                // *** End programmer edit section *** (Товар.Поставщик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Поставщик Set start)

                // *** End programmer edit section *** (Товар.Поставщик Set start)
                this.fПоставщик = value;
                // *** Start programmer edit section *** (Товар.Поставщик Set end)

                // *** End programmer edit section *** (Товар.Поставщик Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Производитель CustomAttributes)

        // *** End programmer edit section *** (Товар.Производитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Производитель"})]
        [NotNull()]
        public virtual IIS.Kursovaya.Производитель Производитель
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Производитель Get start)

                // *** End programmer edit section *** (Товар.Производитель Get start)
                IIS.Kursovaya.Производитель result = this.fПроизводитель;
                // *** Start programmer edit section *** (Товар.Производитель Get end)

                // *** End programmer edit section *** (Товар.Производитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Производитель Set start)

                // *** End programmer edit section *** (Товар.Производитель Set start)
                this.fПроизводитель = value;
                // *** Start programmer edit section *** (Товар.Производитель Set end)

                // *** End programmer edit section *** (Товар.Производитель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.Kursovaya.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.Kursovaya.Товар));
                }
            }
        }
    }
}
